// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
let SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// إذا كان VITE_SUPABASE_PUBLISHABLE_KEY لا يبدأ بـ sb_publishable_ أو eyJ... (أي ليس JWT)، استخدم ANON_KEY
if (!SUPABASE_KEY.startsWith('sb_publishable_') && !SUPABASE_KEY.startsWith('eyJ')) {
  SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || '';
}

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Supabase configuration error: Missing URL or Key');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
